### PR TITLE
[Testing] Updated the item system & Issue fixes

### LINKED ISSUE #61: Leaves Decay
Leaves of non-tree plants (like Tea-leaf) just decay. It makes heads and saplings leavitate. Sometimes even plant lossage.

### LINKED ISSUE #88: Plants Reappear
## Description (Required)
When a player breaks a plant, the plugin doesn't remove the block storage data for the plant, so if someone for example places a block in that spot and right clicks after restart, the plant will reappear destroying the block.

## Steps to reproduce the Issue (Required)
Plant a crop
Break the crop
Place a chest or block
Server restart or possibly when slimefun saves block data
Right click that block or chest
Block or Chest gets destroyed and plant reappears
## Expected behavior (Required)
It should not do this, it should remove block data on break

## Server Log / Error Report
No errors at all

## Environment (Required)

 - Minecraft Version: 1.14.4
 - CS-CoreLib Version: Build 76
 - Slimefun Version: Build 258
 - ExoticGarden Version: Build 21

### LINKED ISSUE #90: Breaking Tilled land that was tilled by a crook gives you more crooks
## Description (Required)
If you break farmland that was tilled by a crook it drops a new crook. Esentially duping crooks.

## Steps to reproduce the Issue (Required)
Get a crook
Till dirt with crook
Break the farmland
https://youtu.be/d9829trnJCY

## Expected behavior (Required)
Just a dirt block to drop, no crook.

## Environment (Required)
image

### PR DESCRIPTION
**Pull request by SoSeDiK**
- Resolves #61.
- Resolves #88.
- Resolves #90.
- Updated all of the items to use the new item system.
- All of the items that could use alternative materials now use only textured heads (also uses API's implementation from now).
- Crook now drops saplings instead of leaves as it's supposed to.
- Grass Seeds are no longer consumed while in creative mode.
- Improved kitchen's handler.
- Updated dependencies and plugin's version.

### CODE REVIEW

**Comment by TheBusyBiscuit** [comment]
Hey, I just wanna inform you that your Pull Requests don't go unnoticed!
Awesome work.

I just don't have any time to review them since they are so huge and I have very few free time.
So please be patient with me, I am not forgetting about them!

**Comment by ericbarbwire** [comment]
This is huge, we need something like this for 1.15 Slimefun very soon

File: src/me/mrCookieSlime/ExoticGarden/items/GrassSeeds.java [hunk 1]
```diff
@@ -6,26 +6,26 @@
...
 	@Override
 	public ItemInteractionHandler getItemHandler() {
 		return (e, p, item) -> {
-			if (SlimefunManager.isItemSimiliar(item, getItem(), true)) {
+			if (isItem(item)) {
 				Block b = e.getClickedBlock();
 				if (b != null && b.getType() == Material.DIRT) {
-					PlayerInventory.consumeItemInHand(p);
+					ItemStack hand = e.getPlayer().getInventory().getItemInMainHand();
+					hand.setAmount(hand.getAmount() - 1);
```
Comment (TheBusyBiscuit) [inline src/me/mrCookieSlime/ExoticGarden/items/GrassSeeds.java]: .setAmount() can cause a lot of problems sometimes.
It is much safer to use ItemUtils.consume or what it's called from CS-CoreLib2.

File: src/me/mrCookieSlime/ExoticGarden/Kitchen.java [hunk 2]
```diff
@@ -30,10 +30,10 @@
 	
 	public Kitchen(ExoticGarden plugin) {
 		super(
-			Categories.MACHINES_1, new CustomItem(Material.CAULDRON, "&eKitchen", new String[] {"", "&a&oYou can make a bunch of different yummies here!", "&a&oThe result goes in the Furnace output slot"}), "KITCHEN",
+			Categories.MACHINES_1, new CustomItem(Material.CAULDRON, "&eKitchen", "", "&a&oYou can make a bunch of different yummies here!", "&a&oThe result goes in the Furnace output slot"), "KITCHEN",
```
Comment (TheBusyBiscuit) [inline src/me/mrCookieSlime/ExoticGarden/Kitchen.java]: Could you maybe convert this to a SlimefunItemStack too?

File: src/me/mrCookieSlime/ExoticGarden/Kitchen.java [hunk 3]
```diff
@@ -83,27 +83,26 @@ public void onInteract(Player p, Block b) {
...
 								if (inv.getContents()[j].getType() != Material.AIR) {
-									if (inv.getContents()[j].getType().toString().endsWith("_BUCKET")) inv.setItem(j, new ItemStack(Material.BUCKET));
-									else if (inv.getContents()[j].getAmount() > 1) inv.setItem(j, new CustomItem(inv.getContents()[j], inv.getContents()[j].getAmount() - 1));
-									else inv.setItem(j, null);
+									if (inv.getContents()[j].getType().toString().endsWith("_BUCKET"))
+										inv.setItem(j, new ItemStack(Material.BUCKET));
+									else if (inv.getContents()[j].getAmount() > 1)
+										inv.setItem(j, new CustomItem(inv.getContents()[j], inv.getContents()[j].getAmount() - 1));
+									else
+										inv.setItem(j, null);
```
Comment (TheBusyBiscuit) [inline src/me/mrCookieSlime/ExoticGarden/Kitchen.java]: I think all of this could be reduced to a single call to ItemUtils.consume(...)

File: src/me/mrCookieSlime/ExoticGarden/EGPlant.java [hunk 4]
```diff
@@ -11,21 +12,21 @@
...
+		super(category, item, recipeType, recipe);
 		this.edible = edible;
 	}
 
 	public boolean isEdible() {
 		return this.edible;
 	}
 
-	private static final int food = 2;
+	private static final int FOOD = 2;
```
Comment (TheBusyBiscuit) [inline src/me/mrCookieSlime/ExoticGarden/EGPlant.java]: Could you maybe move this constant to the top of this file?

File: src/me/mrCookieSlime/ExoticGarden/ExoticGarden.java [hunk 5]
```diff
@@ -74,23 +72,26 @@ public void onEnable() {
...
+			category_drinks = new Category(new CustomItem(SkullItem.fromBase64("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmE4ZjFmNzBlODU4MjU2MDdkMjhlZGNlMWEyYWQ0NTA2ZTczMmI0YTUzNDVhNWVhNmU4MDdjNGIzMTNlODgifX19"), "&aExotic Garden - Drinks", "", "&a> Click to open"));
+			category_magic = new Category(new CustomItem(Material.BLAZE_POWDER, "&5Exotic Garden - Magical Plants", "", "&a> Click to open"));
+
+			SlimefunItemStack iceCube = new SlimefunItemStack("ICE_CUBE", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTM0MGJlZjJjMmMzM2QxMTNiYWM0ZTZhMWE4NGQ1ZmZjZWNiYmZhYjZiMzJmYTdhN2Y3NjE5NTQ0MmJkMWEyIn19fQ==", "&bIce Cube");
+			new SlimefunItem(Categories.MISC, iceCube, RecipeType.GRIND_STONE,
+			new ItemStack[] {new ItemStack(Material.ICE), null, null, null, null, null, null, null, null}, new CustomItem(iceCube, 4))
+			.register();
+		} catch (Exception e) {
+			e.printStackTrace();
+		}
```
Comment (TheBusyBiscuit) [inline src/me/mrCookieSlime/ExoticGarden/ExoticGarden.java]: You can remove this try/catch, it isn't needed here.

File: src/me/mrCookieSlime/ExoticGarden/ExoticGarden.java [hunk 6]
```diff
@@ -698,35 +699,37 @@ public void onDisable() {
...
 		.register();
 
 		try {
-			new EGPlant(category_main, new CustomItem(getSkull(material, texture), color + StringUtils.format(fruitName)), fruitName, new RecipeType(new CustomItem(Material.OAK_LEAVES, "&7Obtained by harvesting the specific Tree")), true,
+			new EGPlant(category_main, new SlimefunItemStack(id, texture, color + name), new RecipeType(new CustomItem(Material.OAK_LEAVES, "&7Obtained by harvesting the specific Tree")), true,
 			new ItemStack[] {null, null, null, null, getItem(id + "_SAPLING"), null, null, null, null})
 			.register();
 		} catch (Exception e1) {
 			e1.printStackTrace();
 		}
```
Comment (TheBusyBiscuit) [inline src/me/mrCookieSlime/ExoticGarden/ExoticGarden.java]: You can remove this try/catch, it isn't needed here.

File: src/me/mrCookieSlime/ExoticGarden/ExoticGarden.java [hunk 7]
```diff
@@ -698,35 +699,37 @@ public void onDisable() {
...
 
 		if (pie) {
 			try {
-				new CustomFood(category_food, new CustomItem(getSkull(Material.PUMPKIN_PIE, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzQxOGM2YjBhMjlmYzFmZTc5MWM4OTc3NGQ4MjhmZjYzZDJhOWZhNmM4MzM3M2VmM2FhNDdiZjNlYjc5In19fQ=="), color + StringUtils.format(fruitName) + " Pie", "", "&7&oRestores &b&o" + "6.5" + " &7&oHunger"), fruitName + "_PIE",
-				new ItemStack[] {getItem(fruitName), new ItemStack(Material.EGG), new ItemStack(Material.SUGAR), new ItemStack(Material.MILK_BUCKET), SlimefunItems.WHEAT_FLOUR, null, null, null, null},
+				new CustomFood(category_food, new SlimefunItemStack(id + "_PIE", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzQxOGM2YjBhMjlmYzFmZTc5MWM4OTc3NGQ4MjhmZjYzZDJhOWZhNmM4MzM3M2VmM2FhNDdiZjNlYjc5In19fQ==", color + name + " Pie", "", "&7&oRestores &b&o" + "6.5" + " &7&oHunger"),
+				new ItemStack[] {getItem(id), new ItemStack(Material.EGG), new ItemStack(Material.SUGAR), new ItemStack(Material.MILK_BUCKET), SlimefunItems.WHEAT_FLOUR, null, null, null, null},
 				13)
 				.register();
 			} catch (Exception e) {
```
Comment (TheBusyBiscuit) [inline src/me/mrCookieSlime/ExoticGarden/ExoticGarden.java]: You can remove this try/catch, it isn't needed here.

File: src/me/mrCookieSlime/ExoticGarden/ExoticGarden.java [hunk 8]
```diff
@@ -742,31 +745,33 @@ public void registerBerry(String name, String color, Color pcolor, PlantType typ
...
 			new ItemStack[] {null, new ItemStack(Material.BREAD), null, null, getItem(name.toUpperCase() + "_JUICE"), null, null, new ItemStack(Material.BREAD), null},
 			16)
 			.register();
 
-			new CustomFood(category_food, new CustomItem(getSkull(Material.PUMPKIN_PIE, "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzQxOGM2YjBhMjlmYzFmZTc5MWM4OTc3NGQ4MjhmZjYzZDJhOWZhNmM4MzM3M2VmM2FhNDdiZjNlYjc5In19fQ=="), color + name + " Pie", "", "&7&oRestores &b&o" + "6.5" + " &7&oHunger"), name.toUpperCase() + "_PIE",
+			new CustomFood(category_food, new SlimefunItemStack(name.toUpperCase() + "_PIE", "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzQxOGM2YjBhMjlmYzFmZTc5MWM4OTc3NGQ4MjhmZjYzZDJhOWZhNmM4MzM3M2VmM2FhNDdiZjNlYjc5In19fQ==", color + name + " Pie", "", "&7&oRestores &b&o" + "6.5" + " &7&oHunger"),
 			new ItemStack[] {getItem(name.toUpperCase()), new ItemStack(Material.EGG), new ItemStack(Material.SUGAR), new ItemStack(Material.MILK_BUCKET), SlimefunItems.WHEAT_FLOUR, null, null, null, null},
 			13)
 			.register();
```
Comment (TheBusyBiscuit) [inline src/me/mrCookieSlime/ExoticGarden/ExoticGarden.java]: You can remove this try/catch, it isn't needed here.

File: src/me/mrCookieSlime/ExoticGarden/ExoticGarden.java [hunk 9]
```diff
@@ -843,24 +841,26 @@ public static ItemStack harvestPlant(Block block) {
...
 								plant = block.getRelative(BlockFace.DOWN);
-								BlockStorage.retrieve(block);
+								BlockStorage.clearBlockInfo(block);
 								block.getWorld().playEffect(block.getLocation(), Effect.STEP_SOUND, Material.OAK_LEAVES);
-								block.setType(Material.AIR);;
+								block.setType(Material.AIR);
 							}
 							plant.setType(Material.OAK_SAPLING);
 							itemstack = berry.getItem();
+							BlockStorage._integrated_removeBlockInfo(plant.getLocation(), false);
```
Comment (TheBusyBiscuit) [inline src/me/mrCookieSlime/ExoticGarden/ExoticGarden.java]: Is this safe to use here?

File: src/me/mrCookieSlime/ExoticGarden/ExoticGarden.java [hunk 10]
```diff
@@ -843,24 +841,26 @@ public static ItemStack harvestPlant(Block block) {
...
 							BlockStorage.store(plant, getItem(berry.toBush()));
 							break;
 						}
 						default: {
 							block.setType(Material.OAK_SAPLING);
 							itemstack = berry.getItem();
+							BlockStorage._integrated_removeBlockInfo(block.getLocation(), false);
```
Comment (TheBusyBiscuit) [inline src/me/mrCookieSlime/ExoticGarden/ExoticGarden.java]: Is this safe to use here?

File: src/me/mrCookieSlime/ExoticGarden/ExoticGarden.java (hunk 9 above)
Comment (SoSeDiK) [reply src/me/mrCookieSlime/ExoticGarden/ExoticGarden.java]: I didn't have issues with it while running a server.
The problem here is that we are adding the new block data at the same time as removing the old one *(like `ID` berry -> `ID_BUSH` upon harvesting)*, which is not normally possible. Methods like `clearBlockInfo(loc)` add block into the ticker task, so upon removing we'll have two entries in the memory for the same location, which causes a lot of problems *(issues #61 and #88)*. This forces Slimefun to remove the data immediately.

Comment (TheBusyBiscuit) [reply src/me/mrCookieSlime/ExoticGarden/ExoticGarden.java]: Alright, thanks for the clarification

File: src/me/mrCookieSlime/ExoticGarden/PlantData.java [hunk 11]
```diff
@@ -2,22 +2,12 @@
...
 		this.texture = texture;
 	}
 
-	public byte toByte() {
-		return data;
-	}
-
 	public String getTexture() {
 		return texture;
 	}
```
Comment (TheBusyBiscuit) [inline src/me/mrCookieSlime/ExoticGarden/PlantData.java]: Isn't this entire class basically useless if it only stores one String?
I think we can remove this class.

Otherwise, this PR is ready for being merged!
Happy holidays btw

**Comment by angelknight89** [comment]
so i loaded exotic garden on my server but for some reason it wont show up and when i finally get it to when the server restarts it goes away is there anyway to stop this?

**Comment by SoSeDiK** [comment]
@angelknight89 Can you provide your logs?
My only guess right now is that auto-update is enabled for EG, but your server's version is not compatible with it (1.14+).
Also, you can use Slimefun's Discord for asking for some help. There's ExoticGarden's channel there too.
